name: Generate UML Diagrams

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  generate-uml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}  # Checkout the branch that triggered the workflow
          
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Install tplant
      run: npm install -g tplant@3.1.0

    - name: Generate PlantUML class diagram from source
      run: tplant -i src/lib/famix/**/*.ts -o doc-uml/famix-typescript-model.puml

    - name: Generate SVG Diagram from PlantUML
      uses: Timmy/plantuml-action@v1
      with:
        args: -v -config "doc-metamodel/skins.include.cfg" -tsvg doc-uml/famix-typescript-model.puml

    - name: Check if UML files have changed
      id: check_changes
      run: |
        git fetch origin
        git diff --exit-code origin/${{ github.ref }} -- doc-uml/famix-typescript-model.puml doc-uml/famix-typescript-model.svg || echo "Files have changed"
  
    - name: Push docs to current branch
      if: steps.check_changes.outputs.changed == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add -v doc-uml
        git commit -v -m "Update docs for branch ${{ github.ref_name }}"
        git push origin HEAD:refs/heads/${{ github.ref_name }}  # Push to the branch that triggered the workflow
